language: ruby
rvm:
  - 1.9.3
before_install:
  # based on https://github.com/heynemann/skink.vnext/blob/master/.skink.yml
  - sudo apt-get install wget
  - sudo wget http://mac4deb.googlepages.com/addrepo -O /usr/bin/addrepo
  - sudo chmod +x /usr/bin/addrepo
  - addrepo deb http://download.virtualbox.org/virtualbox/debian oneiric contrib
  - wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O - | sudo apt-key add -

  - sudo apt-get update
  - sudo apt-get install -y build-essential linux-headers-$(uname -r) dkms
  - sudo apt-get install -y virtualbox-4.2
  - wget http://download.virtualbox.org/virtualbox/4.2.0/Oracle_VM_VirtualBox_Extension_Pack-4.2.0-80737.vbox-extpack && sudo VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-4.2.0-80737.vbox-extpack && rm Oracle_VM_VirtualBox_Extension_Pack-4.2.0-80737.vbox-extpack
  - sudo adduser `whoami` vboxusers

  - VBoxManage --version
install:
  - sh setup.sh
script:
  - bundle exec rake rspec spec
after_script:
  - rm -f elecoma-vagrant-ssh.conf
  - bundle exec vagrant destroy -f
